name: Weekly Twitter Report

on:
  # Run manually from the Actions tab
  workflow_dispatch:

  # Uncomment to auto-run every Friday at 12:00 UTC (adjust as needed)
  # schedule:
  #   - cron: "0 12 * * 5"   # min hr dom mon dow (5 = Friday)

  # (Optional) run when main branch changes scraping/data code
  # push:
  #   branches: [ "main" ]
  #   paths:
  #     - "generate_report.R"
  #     - "DESCRIPTION"
  #     - "renv.lock"
  #     - ".github/workflows/weekly-report.yml"

jobs:
  build-run:
    runs-on: ubuntu-latest

    env:
      # ---------- Supabase ----------
      SUPABASE_HOST:       ${{ secrets.SUPABASE_HOST }}
      SUPABASE_PORT:       ${{ secrets.SUPABASE_PORT }}
      SUPABASE_DB:         ${{ secrets.SUPABASE_DB }}
      SUPABASE_USER:       ${{ secrets.SUPABASE_USER }}
      SUPABASE_PWD:        ${{ secrets.SUPABASE_PWD }}
      SUPABASE_URL:        ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      SB_BUCKET:           ${{ vars.SB_BUCKET || 'weekly-reports' }}

      # ---------- OpenAI ----------
      OPENAI_API_KEY:      ${{ secrets.OPENAI_API_KEY }}

      # ---------- Mailjet ----------
      MJ_API_KEY:          ${{ secrets.MJ_API_KEY }}
      MJ_API_SECRET:       ${{ secrets.MJ_API_SECRET }}
      MAIL_FROM:           ${{ vars.MAIL_FROM }}   # e.g. "José Peña <jgpena@uc.cl>"
      MAIL_TO:             ${{ vars.MAIL_TO }}     # e.g. "ecotools@arweave.org.com"

      # Make non-interactive so installs don't block
      R_KEEP_PKG_SOURCE: no
      CI: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1 \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            xvfb \
            chromium-browser || true
          # Some runners ship chromium via snap; also try google-chrome
          if ! command -v chromium-browser >/dev/null 2>&1; then
            sudo apt-get install -y google-chrome-stable || true
          fi

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::lubridate
            any::httr2
            any::httr
            any::jsonlite
            any::glue
            any::pagedown
            any::RPostgres
            any::DBI
            any::base64enc
            any::tidytext

      - name: Confirm Chrome path (optional debug)
        run: |
          which chromium-browser || echo "no chromium-browser"
          which google-chrome || echo "no google-chrome"
          Rscript -e 'cat("pagedown::find_chrome() ->", pagedown::find_chrome(), "\n")'

      - name: Run report script
        run: |
          Rscript generate_report.R

      - name: Upload generated artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: weekly-report-artifacts
          path: |
            summary.md
            summary_full.pdf
          if-no-files-found: warn
