name: Weekly Twitter Report

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 12 * * 5"     # Fridays @ 12:00 UTC (optional)

jobs:
  build-run:
    runs-on: ubuntu-latest

    env:
      # Supabase
      SUPABASE_HOST:         ${{ secrets.SUPABASE_HOST }}
      SUPABASE_PORT:         ${{ secrets.SUPABASE_PORT }}
      SUPABASE_DB:           ${{ secrets.SUPABASE_DB }}
      SUPABASE_USER:         ${{ secrets.SUPABASE_USER }}
      SUPABASE_PWD:          ${{ secrets.SUPABASE_PWD }}
      SUPABASE_URL:          ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      SB_BUCKET:             ${{ vars.SB_BUCKET || 'weekly-reports' }}

      # OpenAI
      OPENAI_API_KEY:        ${{ secrets.OPENAI_API_KEY }}

      # Mailjet (optional now)
      MJ_API_KEY:            ${{ secrets.MJ_API_KEY }}
      MJ_API_SECRET:         ${{ secrets.MJ_API_SECRET }}
      MAIL_FROM:             ${{ vars.MAIL_FROM }}
      MAIL_TO:               ${{ vars.MAIL_TO }}

      # Disable email sending
      SEND_EMAIL:            "false"

      CI: true
      R_KEEP_PKG_SOURCE: no

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install headless Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2
        with:
          install-dependencies: true
          chrome-version: stable

      - name: Export CHROME_BIN
        run: echo "CHROME_BIN=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV

      - name: Install system libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libfontconfig1 libharfbuzz-dev libfribidi-dev \
            libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::lubridate
            any::httr2
            any::httr
            any::jsonlite
            any::glue
            any::pagedown
            any::rmarkdown
            any::RPostgres
            any::DBI
            any::base64enc
            any::tidytext
            any::magrittr

      - name: Run report script
        run: Rscript generate_report.R

      - name: Upload generated artefacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: weekly-report-artifacts
          path: |
            summary.md
            summary_full.pdf
          if-no-files-found: warn
